const predefinedRoomDetails = {
    1: { status: "Free", patient: null },
    2: { status: "Free", patient: null },
    3: { status: "Free", patient: null },
    4: { status: "Free", patient: null },
    5: { status: "Free", patient: null },
    6: { status: "Occupied", patient: { name: "John Doe", surgery: "Appendectomy" } },
    7: { status: "Occupied", patient: { name: "Mark Johnson", surgery: "Knee Surgery" } },
    8: { status: "Free", patient: null },
    9: { status: "Occupied", patient: { name: "Anna Lee", surgery: "Heart Surgery" } },
    10: { status: "Occupied", patient: { name: "Chris Brown", surgery: "Cataract Surgery" } },
    11: { status: "Free", patient: null },
    12: { status: "Under Maintenance", patient: null },
    13: { status: "Under Maintenance", patient: null },
    14: { status: "Free", patient: null },
    15: { status: "Free", patient: null },
    16: { status: "Occupied", patient: { name: "Sophia Martinez", surgery: "Spine Surgery" }},
    17: { status: "Free", patient: null },
    18: { status: "Free", patient: null },
    19: { status: "Occupied", patient: { name: "Daniel White", surgery: "Liver Transplant" } },
    20: { status: "Occupied", patient: { name: "Michael Clarke", surgery: "Gallbladder Surgery" } },
    21: { status: "Occupied", patient: { name: "Jane Smith", surgery: "Hip Replacement" } },
    22: { status: "Occupied", patient: { name: "Liam Brown", surgery: "Lung Surgery" } },
    23: { status: "Occupied", patient: { name: "Sophia Martinez", surgery: "Spine Surgery" } },
    24: { status: "Free", patient: null },
    25: { status: "Occupied", patient: { name: "Emma Davis", surgery: "Brain Surgery" } },
    26: { status: "Occupied", patient: { name: "Oliver Wilson", surgery: "Heart Bypass" } },
    27: { status: "Occupied", patient: { name: "Charlotte Green", surgery: "Stomach Surgery" } },
    28: { status: "Free", patient: null },

    29: { status: "Free", patient: null },
    30: { status: "Free", patient: null },
    31: { status: "Free", patient: null },
    32: { status: "Occupied", patient: { name: "Sarah Taylor", surgery: "Kidney Transplant" } },
    33: { status: "Free", patient: null },
    34: { status: "Free", patient: null },
    35: { status: "Free", patient: null },
    36: { status: "Free", patient: null },
    37: { status: "Free", patient: null },
    38: { status: "Free", patient: null },
    39: { status: "Free", patient: null },
    40: { status: "Free", patient: null },
    41: { status: "Free", patient: null },
    42: { status: "Occupied", patient: { name: "Noah Lee", surgery: "Hand Surgery" } },
    43: { status: "Free", patient: null },
    44: { status: "Free", patient: null },
    45: { status: "Free", patient: null },
    46: { status: "Free", patient: null },
};

export const roomInformation = Object.entries(predefinedRoomDetails).map(([roomId, details]) => ({
    roomId: Number(roomId),
    status: details.status,
    position: { x: (roomId % 13) * 5, y: 0, z: Math.floor(roomId / 13) * 5 },
    patient: details.patient,
}));
