@startuml
title "Request to update medical condition"

actor Admin
participant "System" as Sys

Admin -> Sys : Request to search medical conditions
activate Sys
Sys --> Admin: Display list of medical conditions
deactivate Sys

opt
Admin -> Sys: Change filters
activate Sys
Sys --> Admin: Display list of medical conditions
deactivate Sys
end

Admin -> Sys : Select medical condition to update
activate Sys
Sys --> Admin: Display medical condition information
deactivate Sys

Admin -> Sys : Change medical condition information and submit
activate Sys
Sys --> Admin: Display success
deactivate Sys

@enduml
