@startuml
title "List Operation requests"
participant "BackEnd" as BackEnd


-> BackEnd : List Operation requests with/out filters
activate BackEnd
BackEnd -> BackEnd : Add(DTO)

alt Doctor not allowed
         <--BackEnd : response status 405 
else Operation Rquest not found
         <--BackEnd : response status 404 
else Operation Request successfully
         <--BackEnd : response status 200
deactivate BackEnd
end

-> BackEnd : Edit/delete Operation requests
activate BackEnd

BackEnd -> BackEnd : Edit or Delete

alt Operation Rquest not found
         <--BackEnd : response status 404 
else Operation Request successfully
         <--BackEnd : response status 200
deactivate BackEnd
end
@enduml
