@startuml

participant "StaffController" as Controller
participant "StaffService" as Service
participant "StaffRepository" as Repository
participant "Staff" as Staff
database "Database" as database

<-- Controller : Request to insert staff
activate Controller
Controller -> Service : Add(DTO)
activate Service

Service -> Staff : create()
alt Invalid Data
        Service --> Controller : status 400
        <-- Controller : status 400
end

Service -> Repository : Add(staff)
activate Repository
        Repository->database : Add(staff)
Repository -> Service : Return success
deactivate Repository



alt Staff updated successfully
        Service --> Controller : status 200
        deactivate Service

        <--Controller : status 200
end
deactivate Controller

@enduml
