@startuml
title "Search/List operation requests"

actor Doctor
participant "System" as Sys



Doctor -> Sys : Request to update an operation requesition
activate Sys


alt Doctor not Allowed
        Doctor <--Sys : response status 405 
else Operation Request successfully
        Doctor <--Sys : response status 200
deactivate Sys
end


@enduml
