// <auto-generated />
using System;
using BackEnd.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(BackEnd_DbContext))]
    [Migration("20241026151233_Domain2")]
    partial class Domain2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppointmentStaff", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("StaffAutoId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId", "StaffAutoId");

                    b.HasIndex("StaffAutoId");

                    b.ToTable("AppointmentStaff");
                });

            modelBuilder.Entity("BackEnd.Domain.Appointments.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OriginatingOnId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OriginatingOnId");

                    b.HasIndex("RoomId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationRequests.OperationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OperationTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientAutoId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedByDoctorAutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("PatientAutoId");

                    b.HasIndex("RequestedByDoctorAutoId");

                    b.ToTable("OperationRequest");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationTypes.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("OperationType");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationTypes.OperationTypePhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("OperationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationTypeId");

                    b.ToTable("OperationTypePhase");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationTypes.OperationTypePhaseSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("OperationTypePhaseId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationTypePhaseId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("OperationTypePhaseSpecialization");
                });

            modelBuilder.Entity("BackEnd.Domain.Patients.Patient", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AppointmentHistory")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Id")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MedicalRecord")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("AutoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("BackEnd.Domain.Shared.DateTimeTuple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("StaffAutoId")
                        .HasColumnType("int");

                    b.Property<int?>("SurgeryRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StaffAutoId");

                    b.HasIndex("SurgeryRoomId");

                    b.ToTable("DateTimeTuple");
                });

            modelBuilder.Entity("BackEnd.Domain.Shared.SystemChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("LogType")
                        .HasColumnType("longtext");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ChangeDate");

                    b.HasIndex("Table");

                    b.HasIndex("TableId");

                    b.ToTable("SystemChangeLog");
                });

            modelBuilder.Entity("BackEnd.Domain.Specializations.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Specialization");
                });

            modelBuilder.Entity("BackEnd.Domain.Staffs.Staff", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("AutoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("SpecializationId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("BackEnd.Domain.SurgeryRooms.SurgeryRoom", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AssignedEquipment")
                        .HasColumnType("longtext");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("SurgeryRoom");
                });

            modelBuilder.Entity("BackEnd.Domain.SurgeryRooms.SurgeryRoomStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SurgeryRoomStatus");
                });

            modelBuilder.Entity("BackEnd.Domain.SurgeryRooms.SurgeryRoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SurgeryRoomType");
                });

            modelBuilder.Entity("AppointmentStaff", b =>
                {
                    b.HasOne("BackEnd.Domain.Appointments.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Staffs.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffAutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Domain.Appointments.Appointment", b =>
                {
                    b.HasOne("BackEnd.Domain.OperationRequests.OperationRequest", "OriginatingOn")
                        .WithMany()
                        .HasForeignKey("OriginatingOnId");

                    b.HasOne("BackEnd.Domain.SurgeryRooms.SurgeryRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.OwnsOne("BackEnd.Domain.Appointments.AppointmentStatus", "Status", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointment");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("OriginatingOn");

                    b.Navigation("Room");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationRequests.OperationRequest", b =>
                {
                    b.HasOne("BackEnd.Domain.OperationTypes.OperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("OperationTypeId");

                    b.HasOne("BackEnd.Domain.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientAutoId");

                    b.HasOne("BackEnd.Domain.Staffs.Staff", "RequestedByDoctor")
                        .WithMany()
                        .HasForeignKey("RequestedByDoctorAutoId");

                    b.OwnsOne("BackEnd.Domain.OperationRequests.OperationRequestPriority", "Priority", b1 =>
                        {
                            b1.Property<int>("OperationRequestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.HasKey("OperationRequestId");

                            b1.ToTable("OperationRequest");

                            b1.WithOwner()
                                .HasForeignKey("OperationRequestId");
                        });

                    b.OwnsOne("BackEnd.Domain.OperationRequests.OperationRequestStatus", "Status", b1 =>
                        {
                            b1.Property<int>("OperationRequestId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.HasKey("OperationRequestId");

                            b1.ToTable("OperationRequest");

                            b1.WithOwner()
                                .HasForeignKey("OperationRequestId");
                        });

                    b.Navigation("OperationType");

                    b.Navigation("Patient");

                    b.Navigation("Priority");

                    b.Navigation("RequestedByDoctor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationTypes.OperationTypePhase", b =>
                {
                    b.HasOne("BackEnd.Domain.OperationTypes.OperationType", "OperationType")
                        .WithMany("Phases")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BackEnd.Domain.OperationTypes.OperationTypePhaseName", "Name", b1 =>
                        {
                            b1.Property<int>("OperationTypePhaseId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.HasKey("OperationTypePhaseId");

                            b1.ToTable("OperationTypePhase");

                            b1.WithOwner()
                                .HasForeignKey("OperationTypePhaseId");
                        });

                    b.Navigation("Name");

                    b.Navigation("OperationType");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationTypes.OperationTypePhaseSpecialization", b =>
                {
                    b.HasOne("BackEnd.Domain.OperationTypes.OperationTypePhase", null)
                        .WithMany("NeededSpecializations")
                        .HasForeignKey("OperationTypePhaseId");

                    b.HasOne("BackEnd.Domain.Specializations.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("BackEnd.Domain.Patients.Patient", b =>
                {
                    b.OwnsOne("BackEnd.Domain.Patients.PatientGender", "Gender", b1 =>
                        {
                            b1.Property<int>("PatientAutoId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.HasKey("PatientAutoId");

                            b1.ToTable("Patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientAutoId");
                        });

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("BackEnd.Domain.Shared.DateTimeTuple", b =>
                {
                    b.HasOne("BackEnd.Domain.Staffs.Staff", "Staff")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("StaffAutoId");

                    b.HasOne("BackEnd.Domain.SurgeryRooms.SurgeryRoom", "SurgeryRoom")
                        .WithMany("MaintenanceSlots")
                        .HasForeignKey("SurgeryRoomId");

                    b.Navigation("Staff");

                    b.Navigation("SurgeryRoom");
                });

            modelBuilder.Entity("BackEnd.Domain.Staffs.Staff", b =>
                {
                    b.HasOne("BackEnd.Domain.Specializations.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId");

                    b.OwnsOne("BackEnd.Domain.Staffs.StaffRole", "Role", b1 =>
                        {
                            b1.Property<int>("StaffAutoId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext");

                            b1.HasKey("StaffAutoId");

                            b1.ToTable("Staff");

                            b1.WithOwner()
                                .HasForeignKey("StaffAutoId");
                        });

                    b.Navigation("Role");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("BackEnd.Domain.SurgeryRooms.SurgeryRoom", b =>
                {
                    b.HasOne("BackEnd.Domain.SurgeryRooms.SurgeryRoomStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId");

                    b.HasOne("BackEnd.Domain.SurgeryRooms.SurgeryRoomType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationTypes.OperationType", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("BackEnd.Domain.OperationTypes.OperationTypePhase", b =>
                {
                    b.Navigation("NeededSpecializations");
                });

            modelBuilder.Entity("BackEnd.Domain.Staffs.Staff", b =>
                {
                    b.Navigation("AvailabilitySlots");
                });

            modelBuilder.Entity("BackEnd.Domain.SurgeryRooms.SurgeryRoom", b =>
                {
                    b.Navigation("MaintenanceSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
