@startuml
title "Search Allergy"
actor Doctor

participant "FrontEnd" as spa
participant "BackEnd2" as BackEnd


Doctor->spa: Search Allergy
activate spa
spa-> BackEnd : HTTP Request: GET /allergy
activate BackEnd

alt User not Allowed
    spa<--BackEnd : status 401
    Doctor<-spa: status 401
else Allergy found
    spa<--BackEnd : status 200
    Doctor<-spa: status 200
    deactivate spa
    deactivate BackEnd
end
@enduml
