@startuml
title "Update Patient Medical Record"

actor Doctor

participant "FrontEnd" as spa
participant "BackEnd2" as BackEnd


Doctor->spa:  Update Patient Medical Record
activate spa
spa-> BackEnd :  HTTP Request: PUT /medicalRecords
activate BackEnd

alt User not Allowed
    spa<--BackEnd : status 401
    Doctor<-spa: status 401
else
    spa<--BackEnd : status 200
    Doctor <-spa: status 200
    deactivate spa
    deactivate BackEnd
end


@enduml
