@startuml
title "Inactivate operation type"
participant "FrontEnd" as FrontEnd
participant "BackEnd" as BackEnd

->FrontEnd: onInit()
activate FrontEnd

<--FrontEnd: Display form
deactivate FrontEnd

->FrontEnd: Request to inactivate operation type
activate FrontEnd
FrontEnd-> BackEnd: HTTP Request: DELETE /operationtypes/id
activate BackEnd

BackEnd-->FrontEnd: Return success
deactivate BackEnd
<--FrontEnd: Display success
deactivate FrontEnd

@enduml
