@startuml
title "Request to create appointment"
participant "AppointmentController" as Controller
participant "AppointmentService" as Service
participant "OperationRequestRepo" as ORRepo
participant "SurgeryRoomRepo" as SRRepo
participant "StaffRepo" as SRepo
participant "AppointmentRepo" as ARepo
participant "Appointment" as Appointment
participant "OperationRequest" as OperationRequest
database "Database" as Database

--> Controller: HTTP Request:\nPOST /Appointment
activate Controller

Controller -> Service: createAppointment(operationRequest,\ndatetime,room,phasesStaff[])
activate Service

Service -> ORRepo: getOperationRequest(operationRequest)
activate ORRepo
ORRepo --> Service: return operation request
deactivate ORRepo

Service -> Service: validate that operation request\nis not already scheduled

Service -> SRRepo: getSurgeryRoom(room)
activate SRRepo
SRRepo --> Service: return surgery room
deactivate SRRepo

Service -> ARepo: getAppointmentsByRoom(date,room)
activate ARepo
ARepo --> Service: return list of appointment
deactivate ARepo

Service -> Service: validate that the room is available\nfor the surgery duration

loop for each staff
    Service -> SRepo: getStaff(staff.id)
    activate SRepo
    SRepo --> Service: return staff
    deactivate SRepo

    Service -> Service: validate that staff is required\nby the operation type phase

    Service -> ARepo: getAppointmentByStaff(date,staff)
    activate ARepo
    ARepo --> Service: return staff appointment list
    deactivate ARepo

    Service -> Service: validate that staff is available\nfor the required duration
end

Service -> Appointment: new()
Service -> ARepo: save(appointment)
activate ARepo
ARepo -> Database: save()
ARepo --> Service: return appointment
deactivate ARepo

Service -> OperationRequest: scheduled()

Service --> Controller: return appointment DTO
deactivate Service

<-- Controller: return appointment DTO
deactivate Controller

@enduml
