@startuml
title "Request to inactivate staff"

actor Admin
participant "System" as Sys

Admin -> Sys : Request to inactivate staff
activate Sys

Sys --> Admin: Display current staff list
deactivate Sys

Admin -> Sys : Select staff to inactivate
activate Sys

Sys --> Admin: Display success
deactivate Sys

@enduml
