@startuml
title "Delete Patient Profile"

actor Admin
participant "<<System>>" as Sys

Admin -> Sys : Search for patient profile
activate Sys

alt Patient found
    Admin -> Sys : Confirm deletion
    activate Sys
    Sys -> Admin : Response status 200 (Deleted)
deactivate Sys
else Patient not found
    Admin <-- Sys : Response status 404 (Not Found)
end

deactivate Sys
@enduml
